name: Update File on Main Branch Commit

on:
  push:
    branches:
      - main

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: checkout test-commits
        uses: actions/checkout@v3
      - name: checkout test-gitops
        run:  git clone https://github.com/arham-git-bot/Test-3.git

      - name: configure git
        run: |
          git config --global user.email "arhamsangoi07@wohlig.com"
          git config --global user.name "arham-git-bot"

      - name: Check File Existence
        run: |
          if [ ! -f Test-3/blob/main/hello.txt ]; then
           echo "Error: File not found."
           exit 1
          fi

      - name: Update File
        run: |
          current_count=$(awk '/my commit count is/ {print $5}' Test-3/blob/main/hello.txt)
          new_count=$((current_count + 1))
          sed -i "s/my commit count is : $current_count/my commit count is : $new_count/" Test-3/blob/main/hello.txt

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'arham-git-bot'
          git config --global user.email 'arhamsangoi07@gmail.com'
          git add .
          git commit -m "Update commit count [skip ci]"
          git push
