name: Update File on Main Branch Commit

on:
  push:
    branches:
      - main

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository B
        uses: actions/checkout@v2
        with:
          repository: arham-git-bot/Test-3
          path: repoB

      - name: Update File
        run: |
          current_count=$(awk '/my commit count is/ {print $5}' @github.com/arham-git-bot/Test-3/blob/main/hello.txt)
          new_count=$((current_count + 1))
          sed -i "s/my commit count is : $current_count/my commit count is : $new_count/" @github.com/arham-git-bot/Test-3/blob/main/hello.txt

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'arham-git-bot'
          git config --global user.email 'arhamsangoi07@gmail.com'
          git add .
          git commit -m "Update commit count [skip ci]"
          git push
