name: Update File on Main Branch Commit

on:
  push:
    branches:
      - main

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
      - name: checkout test-commits
        uses: actions/checkout@v3
      - name: commit
        run: |
          git clone https://github.com/arham-git-bot/Test-3.git
          cd Test-3
          git config --global user.email "arhamsangoi07@gmail.com"
          git config --global user.name "arham-git-bot"
          cat hello.txt
          commit_count=$(grep -oP '(?<=commit count is : )\d+' hello.txt)
          new_commit_count=$((commit_count + 50))
          sed -i "s/commit count is : $commit_count/commit count is : $new_commit_count/" hello.txt
          echo "Commit count updated to: $new_commit_count"
          cat hello.txt
          git add .
          git remote set-url origin https://github.com/arham-git-bot/Test-3.git
          git commit -m "test"
          git push origin main
