name: update a file in another repo

on:
  push:
    branches: ['main']
 
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: arham-git-bot/Test-2
          ref: main

      - name: Update File
        run: |
          file_path="./hello.txt"
          commit_count=$(grep -oP 'my commit count is : \K\d+' $file_path)
          new_count=$((commit_count + 50))
          sed -i "s/my commit count is : $commit_count/my commit count is : $new_count/" $file_path

      - name: Commit and Push Changes
        run: |
          git config --global user.email "arhamsangoi07@gmail.com
          git config --global user.name "arham-git-bot"
          git add .
          git commit -m "update file"
          git push -u origin main
